name: # Name of the Catalog Entry
description: |
  # Description of the Catalog Entry
version: 3.2.8
category: database
maintainer: Indy Beck
license: # The license
projectURL: https://hub.docker.com/_/redis/
